version: '3'
services:
  weblate:
    image: weblate/weblate
    container_name: weblate
    ports: 
    - 8096:8080
    tmpfs:
    - /app/cache
    volumes:
    - weblate-data:/app/data
    env_file:
    - ./environment
    restart: always
    depends_on:
    - database
    - cache
    networks:
    - traefik
    - default
  database:
    image: postgres:14-alpine
    env_file:
    - ./environment
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - traefik
      - default
  cache:
    image: redis:6-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
    networks:
      - traefik
      - default
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
networks:
  default:
  traefik:
    external: true
